skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
mzia_contacts = "5gGkH3UrsLWEfJ1EZouzpUeH1UZjiRTkaP7aHHLcin5H"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
